source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'TWTSideMenuViewController', :git => 'https://github.com/twotoasters/TWTSideMenuViewController.git', :tag => 'v0.3'
pod 'WYPopoverController', '~> 0.2.2'